### ISSUE TITLE
Redundant nested folder inside the package?

### ISSUE THREAD

**Issue by bahriddin** [pinzonjulian/all_you_need_is_rails_engines#1]
Hi Julian,
Thank you for the great talk and repo as POC. I am playing around with it for the few days. I should say it works great!
Only thing that I am not so happy about is this pattern `packages/PACKAGE_NAME/app/models/PACKAGE_NAME/...` - package name repeats twice in the path to each file. I understand it is necessary for autoloading them correctly and scoping everything inside `PackageName::` like `Notifications::Recipient`.

I wonder if we can achieve it without inner `PACKAGE_NAME` folder:

- packages
  - PACKAGE_NAME
    - app
      - models
        - user.rb
        - order.rb
      - controllers
        - ...

**Comment by pinzonjulian** [comment]
Hey! Thanks for trying it out 🙏🏽

I know the feeling of having to work with this level of nesting, but I don't know of a way to make it go away since this is at the core of the autoloader's configuration. It is also the default nesting we have all become used to in Ruby and there is a lot of power in this shared knowledge. Also, note that there's nothing stopping you from removing the second pack/component/engine folder in the model/view/controller folder; it just means it will not be namespaced. 

In my talk I show how this might be an editor's UX problem rather than an issue in the technique. You might want to explore ways to configure your particular editor to collapse folders and make it easier to navigate your engine's structure.

**Comment by bahriddin** [comment]
I really appreciate your response, Julian 👍🏼
